### ISSUE TITLE
Mermaid Support

### ISSUE THREAD

**Issue by sollymay** [jannis-baum/Vivify#132]
Would be awesome to see mermaid graphs displayed on the preview.

**Comment by jannis-baum** [comment]
Noted! I have some other things on the todo-list before I would add this, but if you want it sooner rather than later I'd be happy about a PR! :) 

In case you are interested in contributing (or if not for my own future reference):

A quick search for a Mermaid Markdown-It plugin didn't seem like there was a well-maintained and popular one so I would suggest implementing this analogously to how we handle dot/graphviz in `src/parser/dot.ts` by integrating the official parser (https://www.npmjs.com/package/mermaid)

**Comment by tuurep** [comment]
> integrating the official parser

I was looking at how `iamcco/markdown-preview.nvim` does this, and seems like it's just that as well:

https://github.com/iamcco/markdown-preview.nvim/blob/master/app/pages/mermaid.js

**Comment by Tweekism** [comment]
Yeah seems iamcco was just grabbing the the mermaid.min.js from the mermaid package on npm and adding it into his app/_static directory.

In the mermaid package its .../dist/mermaid.min.js

https://www.npmjs.com/package/mermaid/

**Comment by pidgeon777** [comment]
Mermaid.js support would be great!

**Comment by jannis-baum** [comment]
I have 2 other things pending for Vivify, after those are done I'll do this one :)

**Comment by sollymay** [comment]
Awesome! Thank you for implementing this so quickly! I'll test once I get a chance

**Comment by jannis-baum** [comment]
> Awesome! Thank you for implementing this so quickly! I'll test once I get a chance

Great! Let me know in case there's something different from how you expected it :)
