### ISSUE TITLE
Filename can't contain non-ascii character (such as `ä`, `é`)

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify#26]
### Describe the bug

I had a file with letter `ä` in the name. Trying to open this with `viv` opens a `File not found` page.

The address field shows the correct name for the file.

The tab title shows `ä` as `%C3%A4` initially, but if I move the tab around, it then shows the correct name.

### To Reproduce

Vivify version `0.0.3`, browser Firefox

1. Create a file with the name `café.md`
2. Write contents `Foo Bar QuuuX`
3. Open file with `viv café.md`

### Expected behavior

File should be found

### Additional context

I guess it's debatable whether filenames are allowed to contain non-ascii characters.

Also can't handle spaces in filenames (while I don't name files this way myself, I often see it in the wild for whatever reason). Example `Foo Bar.md`

**Comment by jannis-baum** [comment]
> I guess it's debatable whether filenames are allowed to contain non-ascii characters.
>
> Also can't handle spaces in filenames (while I don't name files this way myself, I often see it in the wild for whatever reason). Example Foo Bar.md

😁 If it was up to me files like that would not be allowed haha but we can't change that so good call! Definitely important to fix.

URLs can't have these characters and usually the percentage encoding is used. So my first idea for the fix is:

1. Check whether evil filenames are already correctly percentage-encoded for all the common weird characters. Seems like it they are based on the example you gave.
2. If yes, the problem can be fixed by just percentage-decoding the files from the URLs before looking for them, simple. If not, we can think about (a) just encoding and decoding all filenames (e.g. Base64) or (b) only encoding evil filenames and then serving them on a different route so we know we have to decode.

---

I would be happy about a PR for this or another solution!☺️ If not I'll do it at some point but can't make any promises on the timeline.
